### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by susannemcom** [adamgreenough/nicholas#13]
I know your goal with this platform was a simple blogging system, but would it be possible to add a way to add static pages like an "about" page?

**Comment by adamgreenough** [comment]
Hi Susanne! Very slow reply, sorry, this is now added. I imagine you have found another solution by now but really appreciate the suggestion and hope it will help others. Thank you!

**Comment by adamgreenough** [comment]
Solved in https://github.com/adamgreenough/nicholas/commit/24aa13d42d329fe48f12c2aa4620ac0b9a77a0fa

**Comment by susannemcom** [comment]
Hi Adam!

Thanks for your e-mail!
I’ve found other solutions (eventually went back to Wordpress) but I’ll definitely check it out again. I really liked your little blog script and I’ll need something like it for smaller projects. Thanks for the notification!

Cheers,
Susanne



Il giorno 8 mar 2020, alle ore 17:37, Adam Greenough <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Hi Susanne! Very slow reply, sorry, this is now added. I imagine you have found another solution by now but really appreciate the suggestion and hope it will help others. Thank you!

**Comment by susannemcom** [comment]
Hi again. I'd love to try Nicholas again, but it seems the latest release isn't the latest? I can't see the option for static pages there. I'm not competent with command line so can't use the master version.
