### ISSUE TITLE
Doesn't Work on Localhost

### ISSUE THREAD

**Issue by teamayu** [adamgreenough/nicholas#19]
Hi Adam,

Just trying out your blog system (well, trying to). Hopefully I can get it working.

I have it installed here:
http://localhost/site/blog/

The config is:
'blog_url' => 'http://localhost/site/blog',
'base_url' => '/blog'

But when I launch all I see is "Oops, Error 404" at the following url:
http://localhost/site/blog/

Any ideas? Thank you.

**Comment by teamayu** [comment]
Ok, the issue is with the AltoRouter class, so no problem. However, the system has so many security issues it's unstable to use. Like for example, loading files without checking if they are loading from the parent. Seriously? Schoolboy stuff. I'll find something better, thanks.

**Comment by adamgreenough** [comment]
Hi @teamayu, the `base_url` in your case should have been `/site/blog`I believe but I will do some testing using a plain localhost URL. Thank you for the feedback on security – if you could point me to any specific areas of concern or learning resources on that, I would appreciate the learning opportunity.

**Comment by Iquaridys** [comment]
remove this code $router->setBasePath($config['base_url']);  in index.php
should work fine
