### ISSUE TITLE
Code reviews wanted

### ISSUE THREAD

**Issue by adamgreenough** [adamgreenough/nicholas#6]

**Comment by kamsalisbury** [comment]
Hi Adam, I am really liking Nicholas. The repo says there are RSS and JSON feeds.
I looked and in footer.php there is code to create the link
`<a href="<?= $config['base_url'] ?>/rss/">RSS</a>`
But I do not see how the content of the RSS and JSON feeds are created.
I do not see anything in home.php calling anything to generate the feeds.
